// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sispdwrclzvxjkcrnron.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpc3Bkd3JjbHp2eGprY3Jucm9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTk4OTAsImV4cCI6MjA2OTk5NTg5MH0.YfGxNI0Ws7vfd4ogGpJTz2tNbqMYCjIBgWSpeIjXA8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});